### ISSUE TITLE
Add relevant keywords in package.json

### ISSUE THREAD

**Issue by ramaghanta** [mstssk/sw2dts#10]
First of all, a big Thank You for this package. I didn't want to use swagger-codegen since I didn't want a dependency of having Java installed. So, I searched for an npm package that would produce .d.ts file from swagger.yml and to my surprise couldn't find any. So, I started creating one myself and mid-way, somehow I stumbled upon your package. I absolutely love this and so I trashed my code and started using this. It would be helpful if you can add some keywords in package.json so this package shows up in npm search.

**Comment by mstssk** [comment]
Thank you @ramaghanta !

I added some keywords and published it at v2.1.4.
https://github.com/mstssk/sw2dts/blob/master/package.json#L6-L10
