### ISSUE TITLE
[Feature Request] Swagger enum to TypeScript string literals

### ISSUE THREAD

**Issue by lacolaco** [mstssk/sw2dts#11]
I'd like to make a type definition using string literals to present enum values.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#433-data-type-fields

```
"models": {
    "Order": {
      "id": "Order",
      "properties": {
        "status": {
          "type": "string",
          "description": "Order Status",
          "enum": [
            "placed",
            "approved",
            "delivered"
          ]
        },
      }
    }
  }
```

to

```
export interface Order {
  status?: "placed" | "approved" | "delivered";
}
```

Thanks.

**Comment by mstssk** [comment]
@laco0416 
I released v2.2.0, this version supports `enum` in query parameter's properties.
See https://github.com/mstssk/sw2dts/blob/master/CHANGELOG.md#220-2016-12-26
