### ISSUE TITLE
Error: Target reference is not found: /Email#

### ISSUE THREAD

**Issue by in19farkt** [mstssk/sw2dts#29]
Hello! Please tell me why this [swagger.json](https://jsoneditoronline.org/?id=3a0ac7d8744836b30f66968e91de4e39) throws an error "Target reference is not found: /Email#"?

**Comment by in19farkt** [comment]
With this [swagger.json](https://jsoneditoronline.org/?id=0b9cd454bdb216f3eef1d24cc95ee7d0) everything works correctly.

**Comment by mstssk** [comment]
@in19farkt I am sorry for my late reply.

I think it's a bug. I try to fix it.

**Comment by mstssk** [comment]
I released v2.6.0 to fix this issue.
Thank you for your report.
