### ISSUE TITLE
Allow to generate type from web url directly.

### ISSUE THREAD

**Issue by baoduy** [mstssk/sw2dts#56]
I hope the library could able to generate a type from a web URL directly so no need to download the JSON file again for each generation.

Thanks
Duy

**Comment by mstssk** [comment]
@baoduy Thanks for your report.

I think follwing workaround solves plobrems like that in most cases.

1. Use `curl` or equivalent command in npm-scripts.
    ```json
    {
      "scripts": {
        "sw2dts": "curl https://petstore.swagger.io/v2/swagger.json | sw2dts -o foobar.d.ts"
      }
    }
    ```
2. Run `npm run sw2dts` 

If you know another edge case, please let me know.
